### ISSUE TITLE
Value out-of-bounds upon `setRegisteredSender`

### ISSUE THREAD

**Issue by RielJ** [wormhole-foundation/native-token-transfers#558]
## Description and context

When using a chain where chainId exceeds uint16, the `setRegisteredSender` will fail.

## Steps to reproduce

1. Deploy `CrossChainSender` and `CrossChainReceiver`
2. Use chains that has a chainId greater than uint16
3. Trigger the `setRegisteredSender`

## Experienced behavior

I have this  error
```sh
An unexpected error occurred: value out-of-bounds (argument="sourceChain", value=421614, code=INVALID_ARGUMENT, version=6.13.4)
```
When using Arbitrum sepolia testnet

## Expected behavior

It should determine and allow any chainId values.

## Solution recommendation

Change the `uint16` on `Base.sol`

```sol
  mapping(uint16 => bytes32) registeredSenders;
```

**Comment by nik-suri** [comment]
Closing this issue as it does not refer to functions or files that are present in NTT. The Wormhole protocol spec, which NTT adheres to, also defines chain IDs as `uint16`.
