### ISSUE TITLE
Issues with Program ID Deployment and Missing Files on NTT Solana

### ISSUE THREAD

**Issue by a007mr** [wormhole-foundation/native-token-transfers#567]
Environment Details:
- NTT CLI Version: v1.0.0-beta
- Operating System: MacOS
- Network: Testnet

Issues Description:
1. Program ID Issue:
I'm encountering an issue when deploying an NTT program to Solana. The CLI expects a specific program ID: nttiK1SepaQt6sZ4WGW5whvc9tEnGXGxuKeptcQPCcS. However, the generated keypair has a different public key, leading to a mismatch error.

2. Missing Files Error:
When trying to deploy with the program key specified, we receive a different error:
"Error: No such file or directory (os error 2)"

Steps to Reproduce:
1. Generated new program keypair:
   ```bash
   solana-keygen grind --starts-with ntt:1 --ignore-case
   # Generated: nTTFvvfsf6AZc4dyHXQDUGA114Wq8SusirLEeDt4xpM
   ```

2. Created token and set authority to PDA:
   ```bash
   ntt solana token-authority nTTFvvfsf6AZc4dyHXQDUGA114Wq8SusirLEeDt4xpM
   # Generated PDA: 4w6pPyB1aBxz8Z5g1rbvppPTzk5j9ijguakndYQed7gE
   ```

3. Attempted deployment with program key:
   ```bash
   ntt add-chain Solana --latest --mode burning \
     --token E6KhRFvrDXMe7wKJyvVCYNEgqN2V7AGbqeMhh81g4SU2 \
     --payer ./NTTKqx1enepwyPoYo9mQXajyLpiWkGgvqh8aGcuHz89.json \
     --program-key ./nTTFvvfsf6AZc4dyHXQDUGA114Wq8SusirLEeDt4xpM.json
   ```
   Error: "No such file or directory (os error 2)"

4. Attempted deployment without program key:
   ```bash
   ntt add-chain Solana --latest --mode burning \
     --token E6KhRFvrDXMe7wKJyvVCYNEgqN2V7AGbqeMhh81g4SU2 \
     --payer ./NTTKqx1enepwyPoYo9mQXajyLpiWkGgvqh8aGcuHz89.json
   ```
   Error: "The private key in nttiK1SepaQt6sZ4WGW5whvc9tEnGXGxuKeptcQPCcS.json does not match the existing program ID: nttiK1SepaQt6sZ4WGW5whvc9tEnGXGxuKeptcQPCcS"

Expected Behavior:
1. According to the documentation, we should be able to use any program ID that starts with "ntt" (generated using the grind command)
2. The deployment process should properly create/handle necessary files

Questions:
1. Is this a known limitation in the beta version?
2. Should we be using a specific program ID for testnet deployments?
3. What files are missing and how should they be properly created/handled? All keypair files are present in the root folder (verified multiple times):
   - nTTFvvfsf6AZc4dyHXQDUGA114Wq8SusirLEeDt4xpM.json
   - NTTKqx1enepwyPoYo9mQXajyLpiWkGgvqh8aGcuHz89.json
   The files are accessible and readable, yet the CLI reports "No such file or directory"

**Comment by a007mr** [comment]
Here is the same problem in a newly initiated project.

Environment Details:
NTT CLI Version: v1.1.0 (attempted to use .deployments/Solana-2.1.0)
OS: macOS

Steps to Reproduce:
1. Initialized a new project with ntt init Testnet.
2. Follow NTT guide "Deploy to Solana"
<img width="930" alt="Screenshot 2024-12-03 at 15 31 17" src="https://github.com/user-attachments/assets/e7088e3e-1373-4199-b965-ce6d27b2a985">

Additional Notes:
• The error seems to be related to a version mismatch or missing directory structure.
• Attempted to manually create the directory, but the error persists.

Any guidance or suggestions would be greatly appreciated!

**Comment by chompcoinxyz** [comment]
I solved the problem. It was because I used solana v.1.21.0 instead of v1.18.10.

**Comment by a007mr** [comment]
I solved the problem. It was because I used solana v.1.21.0 instead of v1.18.10.

**Comment by a007mr** [comment]
I solved the problem. It was because I used solana v.1.21.0 instead of v1.18.10.
